modLoader="javafml"
loaderVersion="[47,)"
license="MIT"

[[mods]]
modId="authmod"
version="1.0.0"
displayName="Auth Mod"
description="Simple authentication system"
authors="dQryyx"

[[dependencies.authmod]]
modId="forge"
mandatory=true
versionRange="[47.4.0,)"
ordering="NONE"
side="BOTH"

[[dependencies.authmod]]
modId="minecraft"
mandatory=true
versionRange="[1.20.1,1.21)"
ordering="NONE"
side="BOTH"